# Generated by Django 3.0.2 on 2020-01-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0002_group_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
