# Generated by Django 3.0.2 on 2020-01-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0003_auto_20200123_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='limit',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
