# Generated by Django 3.0.2 on 2020-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0004_timeslot_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='time_chart.User'),
        ),
    ]
