# Generated by Django 3.0.2 on 2020-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0005_auto_20200125_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='people',
            field=models.ManyToManyField(blank=True, to='time_chart.User'),
        ),
    ]
