# Generated by Django 3.0.2 on 2020-03-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0006_auto_20200125_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='week_limit',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
