# Generated by Django 3.0.2 on 2020-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0007_group_week_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='#ffffff00', max_length=9),
        ),
    ]
