# Generated by Django 3.0.2 on 2020-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0008_group_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='limit',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
