# Generated by Django 3.0.2 on 2020-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0009_auto_20200319_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, default=None, to='time_chart.Group'),
        ),
    ]
