# Generated by Django 3.0.7 on 2020-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0010_timeslot_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_chat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
