# Generated by Django 3.0.7 on 2020-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_chart', '0012_auto_20200909_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
